version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/aws-devops-pgp
hooks:
#  BeforeInstall:
 #   - location: scripts/boot.sh
  #    timeout: 200
   #   runas: root

  BeforeAllowTraffic:
    - location: scripts/start.sh
      timeout: 200
      runas: root
